### ISSUE TITLE
Bug: PG's and SG's does not seem to "remove" old streams

### ISSUE THREAD

**Issue by mLgz0rn** [SenexCrenshaw/StreamMaster#107]
**Describe the Bug**

PG's and SG's does not seem to be correctly updated and representing the current streams from the imported m3u.
Looks like streams that are no longer present in the m3u is not getting removed.

![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/9de0754f-782a-48f8-89ab-0f4fc336e9a1)
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/ac28afb9-1b7a-4f3f-bae1-08360549574a)
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6141439/e50dba04-c619-4d2b-93ce-e68368eac2fe)

**Stream Master Info**
- 0.2.18-25

**Comment by aniel300** [comment]
i think i have run into this, deleting the db is the only thing that works for me. not sure if this has been fixed in the latest builds

**Comment by mLgz0rn** [comment]
> i think i have run into this in the past, deleting the db is the only thing that works for me. not sure if this has been fixed in the latest builds

This is the latest

**Comment by aniel300** [comment]
umm the idk, probably the bug still there i just can’t confirm it. i believe i did test this while doing some testing and i thought it was fixed but apparently it is not.


Sent from Yahoo Mail for iPhone


On Friday, October 6, 2023, 3:00 PM, mLgz0rn ***@***.***> wrote:





i think i have run into this in the past, deleting the db is the only thing that works for me. not sure if this has been fixed in the latest builds


This is the latest

**Comment by SenexCrenshaw** [comment]
Streams are based off of urls. If a url changes the old stream will be removed and a new is created.

That's how it's supposed to work with out the bugs.

**Comment by dp247** [comment]
I'll happily help debug/relearn C# to help out - are there any instructions for building from source?
@SenexCrenshaw

**Comment by mLgz0rn** [comment]
There seems to be a somewhat reversed issue of this now with stream groups.
New streams are not being added to stream groups, I have to deselect all playlist groups and select them again.
