### ISSUE TITLE
Feature Request: Stream Group Editor to allow auto-renumbering.

### ISSUE THREAD

**Issue by jimmymarbles** [SenexCrenshaw/StreamMaster#110]
I would like see Stream groups have the functionality of auto-renumbering.  As it is now, you can only auto-renumber in the playlist editor and manually type in channel numbers to individual streams.

**Comment by aniel300** [comment]
u want to auto number all the channels within a group? because if that is the case then sm can do that now

**Comment by jimmymarbles** [comment]
Hmmm, all I saw with the latest build was I can manually type in channel numbers but not auto renumber all streams within a group.   But maybe it's already there as you says aniel300....

**Comment by mLgz0rn** [comment]
> u want to auto number all the channels within a group? because if that is the case then sm can do that now

No it can't

**Comment by aniel300** [comment]
> > u want to auto number all the channels within a group? because if that is the case then sm can do that now
> 
> No it can't

so what is this? @jimmymarbles 
![chrome_4KRmrZE8uA](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/794143b9-db5d-488b-abbe-4e20637a8f0a)
![chrome_W1hGeeQUvj](https://github.com/SenexCrenshaw/StreamMaster/assets/7571729/cb96ef52-29cb-425a-968e-9a2f0b000bf4)

**Comment by jimmymarbles** [comment]
That isn't the Streams Group Editor.  You are in the playlist editor where you can renumber all the channels.  

I would like the ability to auto renumber the groups because not every user will not have access to all the streams.

![image](https://github.com/SenexCrenshaw/StreamMaster/assets/6432197/a35a6b7c-75cc-452c-9311-519819a0613c)

**Comment by aniel300** [comment]
> auto renumber

can u define what "auto renumber" in the group editor means and what is the end goal that u looking for?

**Comment by jimmymarbles** [comment]
So I want the same exact functionality you see in the playlist editor but at the stream group level.  

I have a big m3u file that gets updated every 72hrs and I want to take portions of it and put them in stream groups.   So say a stream group has 25 streams.  I want to renumber the channels to 100-125.  I have another stream group with 50 streams that is used by different users.  I want to renumber it to 100-150. 

If that renumbering at the stream group level wasn't there, then I would have streams with a bunch of "random" numbers based on all the streams from the playlist editor.

**Comment by mLgz0rn** [comment]
> > auto renumber
> 
> can u define what "auto renumber" in the group editor means and what is the end goal that u looking for?

Why does he have to redefine his entire post and reask the same question just so you can understand?
I have no issues understanding what he wants.
This is not your project, stop acting like it....

**Comment by aniel300** [comment]
> > > auto renumber
> > 
> > 
> > can u define what "auto renumber" in the group editor means and what is the end goal that u looking for?
> 
> Why does he have to redefine his entire post and reask the same question just so you can understand? I have no issues understanding what he wants. This is not your project, stop acting like it....

i said define not redefine. and i know this is not my project nor am acting like it is mine. i simply would like to understand the request so we can all be in the same page not to mention that just because u fully understand it doesnt mean others can/or i can whether that is because english is not their native language or because we all human and have different, iq, brains, etc. not sure why the attitude since the question wasn't even for u.

**Comment by aniel300** [comment]
> So I want the same exact functionality you see in the playlist editor but at the stream group level.
> 
> I have a big m3u file that gets updated every 72hrs and I want to take portions of it and put them in stream groups. So say a stream group has 25 streams. I want to renumber the channels to 100-125. I have another stream group with 50 streams that is used by different users. I want to renumber it to 100-150.
> 
> If that renumbering at the stream group level wasn't there, then I would have streams with a bunch of "random" numbers based on all the streams from the playlist editor.
> 
> Now the big assumption is that Plex sooner or later will recognize the channel numbers and sort the streams based on the number. Currently when I import a m3u file from SM, Plex does not show the number, but list the stream name. I'm sure its some formatting thing....

thank you for taking the time to explain this for me (since @mLgz0rn attack me for some reason). now i fully understand and i really like you thinking outside the box here. i personally don't have a use case for this but this is a very good request. have u try setting 2 or more channels with the same chanel number and see if u can still stream said channels right now idk if that is something can do otherwise u might be able to do ur numbering in the playlist section and go from there but if sm cant do that then your request might make @SenexCrenshaw do some restructuring (he would know more on this). if am assuming correctly i think channels with same channel number are meant to be failovers, again all assumptions here and if am not mistaking the channel failover is broken and needs some work i believe.

**Comment by SenexCrenshaw** [comment]
> I would like see Stream groups have the functionality of auto-renumbering. As it is now, you can only auto-renumber in the playlist editor and manually type in channel numbers to individual streams.

It was only matter of time before this was requested. i might just bring the whole bar over from playlist.

**Comment by SenexCrenshaw** [comment]
> I would like see Stream groups have the functionality of auto-renumbering. As it is now, you can only auto-renumber in the playlist editor and manually type in channel numbers to individual streams.

This is in now. it goes by the last thing ordered. if there are dupes in a sorted column (like epgid) than its a little random which one will get the next number.  if this is a HUGE issue open another request to change that.
